<?php

namespace AISeeder\Schema\Constraints;

use Illuminate\Database\Connection;

/**
 * Reads value-list constraints that Laravel's schema builder does not expose,
 * such as the CHECK constraints generated by $table->enum() on pgsql and sqlite.
 */
interface ConstraintReader
{
    /**
     * @return array<string, list<string>> Allowed values keyed by column name.
     */
    public function allowedValues(Connection $connection, string $table): array;
}
