<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Database Connection
    |--------------------------------------------------------------------------
    |
    | The connection RealSeed writes to. Null uses the application's default.
    |
    | Note: the supported environments (local, dev, development, staging) are
    | enforced by the package itself and intentionally cannot be configured.
    |
    */

    'connection' => env('REALSEED_CONNECTION'),

    /*
    |--------------------------------------------------------------------------
    | AI Planning
    |--------------------------------------------------------------------------
    |
    | The AI reads your schema (never your data) and suggests a generation plan:
    | quantities, distributions, workflows, and realistic example values. Every
    | row is still generated by deterministic code.
    |
    | driver:   "laravel-ai" uses the Laravel AI SDK (composer require laravel/ai),
    |           configured in config/ai.php. Or the class name of your own
    |           Ayangzy\RealSeed\AI\AIProviderInterface implementation.
    | provider: laravel/ai provider name (anthropic, openai, gemini, ollama, ...);
    |           null uses the laravel/ai default.
    | model:    model name; null uses the provider default.
    |
    | AI planning is required: RealSeed stops, without changing anything, when
    | the provider can't be used. Set the provider's key in .env, for example
    | OPENAI_API_KEY, or GEMINI_API_KEY with REALSEED_AI_PROVIDER=gemini.
    |
    */

    'ai' => [
        'driver' => env('REALSEED_AI_DRIVER', 'laravel-ai'),
        'provider' => env('REALSEED_AI_PROVIDER'),
        'model' => env('REALSEED_AI_MODEL'),
        'timeout' => (int) env('REALSEED_AI_TIMEOUT', 300), // seconds; large schemas need longer answers
    ],

    /*
    |--------------------------------------------------------------------------
    | Plan Cache
    |--------------------------------------------------------------------------
    |
    | AI plans are saved here as JSON and reused while the schema, scenario and
    | options are unchanged (use --replan to refresh). Commit the directory to
    | share reproducible datasets with your team. Null uses
    | storage/realseed/plans.
    |
    */

    'plans_path' => env('REALSEED_PLANS_PATH'),

    /*
    |--------------------------------------------------------------------------
    | Model Paths
    |--------------------------------------------------------------------------
    |
    | Directories scanned for Eloquent models. Any layout works; add module or
    | domain directories here if your models live outside app/.
    |
    */

    'model_paths' => [
        app_path(),
    ],

    /*
    |--------------------------------------------------------------------------
    | Excluded Tables and Columns
    |--------------------------------------------------------------------------
    |
    | Tables and columns RealSeed never generates data for. Wildcards are
    | supported. Columns use "table.column" or "*.column". Required columns
    | cannot be excluded because inserts would fail without them.
    |
    */

    'excluded_tables' => [
        'migrations',
        'cache',
        'cache_locks',
        'sessions',
        'jobs',
        'job_batches',
        'failed_jobs',
        'password_reset_tokens',
        'personal_access_tokens',
        'telescope_*',
        'pulse_*',
    ],

    'excluded_columns' => [],

    /*
    |--------------------------------------------------------------------------
    | Protected Tables
    |--------------------------------------------------------------------------
    |
    | Tables that hold real data you care about (roles, permissions, plans,
    | your product catalogue, ...). RealSeed never adds rows to them and never
    | deletes from them, not even with --fresh, but still links generated data
    | to their existing rows. Unlike excluded_tables, they stay in the analysis.
    |
    */

    'protected_tables' => [],

    /*
    |--------------------------------------------------------------------------
    | Polymorphic Targets
    |--------------------------------------------------------------------------
    |
    | RealSeed learns what a polymorphic relation can point to from morphMany /
    | morphOne relations on your models, or from types already in the table.
    | When neither exists, list them here:
    |
    |   'bank_accounts.account' => [App\Models\User::class, App\Models\Company::class],
    |
    */

    'morph_targets' => [],

    /*
    |--------------------------------------------------------------------------
    | Generation Defaults
    |--------------------------------------------------------------------------
    |
    | size:     small, medium, or large (overridden by --size)
    | strategy: ai, factory, or hybrid (overridden by --strategy)
    | locale:   a country code (ng, us, gb, ca, au, de, fr, ...), a Faker locale
    |           (pt_BR), or a key from "locales" below (overridden by --locale)
    | currency: ISO code for currency columns; null uses the locale's currency
    |
    */

    'size' => 'medium',

    'strategy' => 'ai',

    'locale' => 'en_US',

    'currency' => null,

    /*
    |--------------------------------------------------------------------------
    | Overrides
    |--------------------------------------------------------------------------
    |
    | Your rules win over heuristics and AI suggestions (never over safety):
    |
    |   'users' => [
    |       'count' => 200,
    |       'states' => ['admin' => 1, 'default' => 20],   // factory states
    |       'fields' => [
    |           'status' => ['weights' => ['active' => 90, 'suspended' => 10]],
    |           'bio' => ['samples' => ['Coffee first.', 'Runner and reader.']],
    |           'phone' => ['semantic' => 'phone', 'null_rate' => 0.2],
    |           'manager_id' => ['null_rate' => 0.5, 'selection' => 'uniform', 'scope' => false],
    |           'deleted_at' => ['null_rate' => 0.98],
    |           'suspended_at' => ['present_when' => ['status' => ['suspended']]],
    |       ],
    |   ],
    |
    */

    'overrides' => [],

    /*
    |--------------------------------------------------------------------------
    | Extensions
    |--------------------------------------------------------------------------
    |
    | generators:        custom FieldGenerator classes by "table.column",
    |                    "*.column", or "semantic:<semantic>"
    | row_generators:    custom RowGenerator classes by table
    | reference_pickers: custom ReferencePicker classes by "table.column"
    | scenarios:         named ScenarioProvider classes, used as --scenario=<name>
    | analyzers:         ApplicationAnalyzer classes applied to every plan
    | locales:           custom LocaleProvider classes by code, used as --locale=<code>
    |
    | Contracts live in Ayangzy\RealSeed\Extension and Ayangzy\RealSeed\Locale.
    |
    */

    'generators' => [],

    'row_generators' => [],

    'reference_pickers' => [],

    'scenarios' => [],

    'analyzers' => [],

    'locales' => [],

    /*
    |--------------------------------------------------------------------------
    | Performance
    |--------------------------------------------------------------------------
    |
    | chunk_size:          maximum rows per INSERT statement
    | existing_rows_limit: existing rows loaded per table to connect new data to
    |
    */

    'chunk_size' => 500,

    // Upper bound on rows per run, whatever a plan or scenario requests.
    'max_rows' => 250000,

    'existing_rows_limit' => 100000,

];
